development:
  adapter: postgresql
  encoding: unicode
  database: aventura_development
  pool: 5
  username: max
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: aventura_test
  pool: 5
  username: max
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: aventura_production
  pool: 5
  username: max
  password: 
  timeout: 5000
