development:
  adapter: postgresql
  encoding: unicode
  database: aventura_development
  pool: 5
  username: max
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: aventura_production
  pool: 5
  username: aventura
  password: PleinAir!
  timeout: 5000
